amcl:
  ros__parameters:
    use_sim_time: false
    min_particles: 500
    max_particles: 5000
    kld_err: 0.05
    kld_z: 0.99
    update_min_d: 0.2
    update_min_a: 0.5
    resample_interval: 1
    transform_tolerance: 1.0
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    odom_alpha1: 0.2
    odom_alpha2: 0.2
    odom_alpha3: 0.2
    odom_alpha4: 0.2
    odom_alpha5: 0.2
    laser_min_range: 0.1
    laser_max_range: 12.0
    laser_max_beams: 60
    odom_frame_id: "odom"
    base_frame_id: "base_footprint"
    scan_topic: "scan"
    map_topic: "map"
    tf_broadcast: true
    always_reset_initial_pose: false
    initial_pose_x: 0.0
    initial_pose_y: 0.0
    initial_pose_a: 0.0
    initial_cov_xx: 0.25
    initial_cov_yy: 0.25
    initial_cov_aa: 0.0685
